### ISSUE TITLE
[QUESTION] -Can't see the diagram on WIN10 system

### ISSUE THREAD

**Issue by qizewen** [opencaesar/oml-theia#20]
## Description
When open the project, can't see the oml diagram on WIN10 system. But if use MAC, it worked.

## Relevant screenshots
On WIN10 system , it will give output as the following figures.

![image](https://user-images.githubusercontent.com/35015805/82875866-8e3e0380-9f6a-11ea-815e-798992a63abb.png)
![image](https://user-images.githubusercontent.com/35015805/82875989-af065900-9f6a-11ea-8b9d-35cefee1ebf5.png)
![image](https://user-images.githubusercontent.com/35015805/82875886-95fda800-9f6a-11ea-81f2-48adb7d92955.png)

**Comment by melaasar** [comment]
In the last screenshot, I see an error about the server JAR file. Can you please tell me what is the name of the files you see in folder oml-theia/oml/build and what are their sizes?

**Comment by melaasar** [comment]
The problem is that the nmp environment variables have a different syntax on Windows than on Max/Linux. The script oml/package.json used a variable for the oml server version, resulting on the server not being downloaded during the yarn build. The solution was to use an npm pacakge called cross-var that can convert the variable names to the proper syntax of the platform. The fix # https://github.com/opencaesar/oml-theia/commit/8b5a956ccd0f0c22bd643572570e1a29546ca68b has been pushed
